// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRx0sZohdvL8fbn_DOvPlu0yZ3CKMs0v4',
    appId: '1:876775281331:web:9dccdbd1daabc27a6716c6',
    messagingSenderId: '876775281331',
    projectId: 'easymelanoscan',
    authDomain: 'easymelanoscan.firebaseapp.com',
    storageBucket: 'easymelanoscan.appspot.com',
    measurementId: 'G-5MPFFE648W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxn9eINfkDoPg6xLmvu_OFHDNF_Ff_Ea8',
    appId: '1:876775281331:android:0a5b92aede0686306716c6',
    messagingSenderId: '876775281331',
    projectId: 'easymelanoscan',
    storageBucket: 'easymelanoscan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTG0VIMB6v69pFSOuxLhG3PG6qEkZe6Y0',
    appId: '1:876775281331:ios:b75a19d9f9bda6886716c6',
    messagingSenderId: '876775281331',
    projectId: 'easymelanoscan',
    storageBucket: 'easymelanoscan.appspot.com',
    iosClientId: '876775281331-gbvuecidvf1rculo56jfmkmpsavpr99b.apps.googleusercontent.com',
    iosBundleId: 'com.example.melanomaDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTG0VIMB6v69pFSOuxLhG3PG6qEkZe6Y0',
    appId: '1:876775281331:ios:8d45d09e093d3e356716c6',
    messagingSenderId: '876775281331',
    projectId: 'easymelanoscan',
    storageBucket: 'easymelanoscan.appspot.com',
    iosClientId: '876775281331-8lif074a57b43npuq4aq15tnlj3v360d.apps.googleusercontent.com',
    iosBundleId: 'com.example.melanomaDetection.RunnerTests',
  );
}
